TirelireWeb/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Tirelire.Data.Data.Repository;
using Tirelire.Models;
using Tirelire.Models.ViewModel;
using Tirelire.Utility;

namespace TirelireWeb.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        [BindProperty]
        public ShoppingCartVM ShoppingCartVM { get; set; }
        public CartController(IUnitOfWork unitOfWork) 
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            //get userId
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            ShoppingCartVM = new()
            {
                ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(u => u.AppUserId == userId,includeProps:"Produit"),
                OrderHeader = new()
            };

            foreach (var cart in ShoppingCartVM.ShoppingCartList) 
            { 
                cart.Price = GetPriceForShoppingCart(cart);
                ShoppingCartVM.OrderHeader.OrderTotal += (cart.Price * cart.Count);
            }
            return View(ShoppingCartVM);
        }

        public IActionResult Summary()
        {
            //get userId
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            ShoppingCartVM = new()
            {
                ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(u => u.AppUserId == userId, includeProps: "Produit"),
                OrderHeader = new()
            };

            //retreive data about appuser to fil ordheader attribut
            ShoppingCartVM.OrderHeader.AppUser = _unitOfWork.AppUser.Get(u=>u.Id == userId);
            ShoppingCartVM.OrderHeader.Nom = ShoppingCartVM.OrderHeader.AppUser.Name;
            ShoppingCartVM.OrderHeader.Email = ShoppingCartVM.OrderHeader.AppUser.Email;

            foreach (var cart in ShoppingCartVM.ShoppingCartList)
            {
                cart.Price = GetPriceForShoppingCart(cart);
                ShoppingCartVM.OrderHeader.OrderTotal += (cart.Price * cart.Count);
            }
            return View(ShoppingCartVM);
        }

        [HttpPost]
        [ActionName("Summary")]
        public IActionResult SummaryPost()
        {
            //get userId
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            ShoppingCartVM.ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(u => u.AppUserId == userId, includeProps: "Produit");
            ShoppingCartVM.OrderHeader.DateCommande = DateTime.Now;
            ShoppingCartVM.OrderHeader.AppUserId = userId;

            foreach (var cart in ShoppingCartVM.ShoppingCartList)
            {
                cart.Price = GetPriceForShoppingCart(cart);
                ShoppingCartVM.OrderHeader.OrderTotal += (cart.Price * cart.Count);
            }

            //capture a payment
            //check current user role to allow payment if client
            if (User.IsInRole("Client"))
            {
                ShoppingCartVM.OrderHeader.PaymentStatus = SD.PaymentStatusPending;
                ShoppingCartVM.OrderHeader.OrderStatus = SD.StatusPending;
                //save orderheader to db
                _unitOfWork.OrderHeader.Add(ShoppingCartVM.OrderHeader);
                _unitOfWork.Save();
                //add new orderdetail
                foreach (var cart in ShoppingCartVM.ShoppingCartList)
                {
                    OrderDetail orderDetail = new()
                    {
                        ProduitId = cart.ProduitId,
                        OrderHeaderId = ShoppingCartVM.OrderHeader.Id,
                        Price = cart.Price,
                        Count = cart.Count
                    };
                    _unitOfWork.OrderDetail.Add(orderDetail);
                    _unitOfWork.Save();
                }
            }

            return RedirectToAction(nameof(OrderConfirmation),new {id=ShoppingCartVM.OrderHeader.Id});
        }


        public ActionResult OrderConfirmation(int id) {
            return View(id);
        }

        public IActionResult Plus(int cartId) 
        { 
            //get a cart from db base on id
            var cartFromDb = _unitOfWork.ShoppingCart.Get(u=>u.Id == cartId);
            cartFromDb.Count += 1;
            _unitOfWork.ShoppingCart.Update(cartFromDb);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(int cartId)
        {
            //get a cart from db base on id
            var cartFromDb = _unitOfWork.ShoppingCart.Get(u => u.Id == cartId);
            _unitOfWork.ShoppingCart.Remove(cartFromDb);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Minus(int cartId)
        {
            //get a cart from db base on id
            var cartFromDb = _unitOfWork.ShoppingCart.Get(u => u.Id == cartId);
            if(cartFromDb.Count <=1)
            {
                //remove
                _unitOfWork.ShoppingCart.Remove(cartFromDb);
            }
            else
            {
                cartFromDb.Count -= 1;
                _unitOfWork.ShoppingCart.Update(cartFromDb);
            }
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }

        private double GetPriceForShoppingCart(ShoppingCart shoppingCart)
        {
            return shoppingCart.Produit.Prix;
        }
    }
}

TirelireWeb/Controllers/TirelireController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Tirelire.Data.Data.Repository;
using Tirelire.Models;
using Tirelire.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Tirelire.Utility;

namespace TirelireWeb.Controllers
{
    [Authorize(Roles =SD.Role_Admin)]
    public class TirelireController : Controller
    {
        //retreive a data from database -> get data throw constructor
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public INotyfService _notifyService { get; }
        public TirelireController(IUnitOfWork unitOfWork, INotyfService notifyService, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _notifyService = notifyService;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            //get a list od Tirelire
            List<Produit> objTirelireList = _unitOfWork.Tirelire.GetAll(includeProps:"Fabricant").ToList();
            //to pass a data to a view
            return View(objTirelireList);
        }

        //add a new action method called upsert 
        public IActionResult Upsert(int? id)
        {
            //ViewBag.FabricantList = FabricantList;
            Produit? tirelireFromDb1 = _unitOfWork.Tirelire.Get(u => u.Id == id);
            TirelireVM tirelireVM = new()
            {
                FabricantList = _unitOfWork.Fabricant.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                Tirelire = new Produit()
            };
            // create if id is not set
            if(id == null || id == 0)
            {
                return View(tirelireVM);
            }
            else
            {
                //edit or update
                tirelireVM.Tirelire = _unitOfWork.Tirelire.Get(u => u.Id == id);
                return View(tirelireVM);
            }
        }

        //add a new action method called upsert with parameter to get submit data
        [HttpPost]
        public IActionResult Upsert(TirelireVM obj, IFormFile? file,int? id)
        {
            //check if model "Tirelire" is valid with all requirement
            if (id.HasValue)
                obj.Tirelire.Id = id.Value;

            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if(file != null)
                {
                    string filename = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string productPath = Path.Combine(wwwRootPath, @"images\produit");

                    //copy a file to a location
                    using (var fileStream = new FileStream(Path.Combine(productPath, filename), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    obj.Tirelire.ImageUrl = @"\images\produit\"+filename;
                }
                if (obj.Tirelire.Id == 0)
                {
                    _unitOfWork.Tirelire.Add(obj.Tirelire);
                    //saves a changes in database
                    _unitOfWork.Save();
                    _notifyService.Success("Tirelire crée avec succes!");
                }
                else
                {
                    _unitOfWork.Tirelire.Update(obj.Tirelire);
                    _unitOfWork.Save();
                    _notifyService.Success("Tirelire modifiée avec succes!");
                }

                //return to index view and reload data
                return RedirectToAction("Index");
            }
            return View();
        }

        //add a new action method called Delete : get
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //Tirelire? TirelireFromDb = _db.Tirelires.Find(id);
            Produit? TirelireFromDb1 = _unitOfWork.Tirelire.Get(u => u.Id == id);
            if (TirelireFromDb1 == null)
            {
                return NotFound();
            }
            return View(TirelireFromDb1);
        }

        //add a new action method called Delete with parameter to get submit data
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Produit? obj = _unitOfWork.Tirelire.Get(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.Tirelire.Remove(obj);
            _unitOfWork.Save();
            _notifyService.Success("Tirelire supprimé avec succes!");
            return RedirectToAction("Index");
        }
    }
}

TirelireWeb/Views/Shared/_DetailPartial.cshtml
<h4><strong>Tirelire avec le même couleur:</strong></h4>
<div class="card-group my-auto">
    @foreach(var tirelire in ViewBag.tirelireWithSameColor){
        <div class="card shadow border 0 ml-1">
            <div class="row">
                <div class="d-none d-lg-block col-lg-1 text-center py-2">
                    <img src="@tirelire.ImageUrl" class="rounded" width="100%" />
                </div>
                <h5 class="card-title">@tirelire.Title</h5>
                <p>@tirelire.Description</p>
                <p><strong>Prix: @tirelire.Prix.ToString("c")</strong></p>
            </div>
        </div>
    }
</div>

TirelireWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TirelireWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TirelireWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/icon/ico.png" width="45" height="45" alt="icon" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <!--check a role of user and authorize access for "Gestionnaire"-->
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Gestionnaire
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-controller="Fabricant" asp-action="Index">Fabricant</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-controller="Tirelire" asp-action="Index">Tirelire</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                </ul>
                            </li>
                        }
                        <form class="d-flex w-50" role="search" id="navBarSearchForm">
                            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
                        </form>
                    </ul>
                    <partial name="_LoginPartial" />
                    <div class="nav-item">
                        <a class="nav-link" asp-controller="Cart" asp-action="Index">
                            <img src="~/icon/cart.png" width="30" height="30"/>
                        </a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-muted">
        <div class="text-center">
            &copy; 2024 - TirelireWeb
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>