TirelireWeb/Controllers/FabricantController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Tirelire.Data.Data.Repository;
using Tirelire.Models;
using Tirelire.Utility;

namespace TirelireWeb.Controllers
{
    [Authorize(Roles =SD.Role_Admin)]
    public class FabricantController : Controller
    {
        //retreive a data from database -> get data throw constructor
        private readonly IUnitOfWork _unitOfWork;
        public INotyfService _notifyService { get; }
        public FabricantController(IUnitOfWork unitOfWork, INotyfService notifyService)
        {
            _unitOfWork = unitOfWork;
            _notifyService = notifyService;
        }
        public IActionResult Index()
        {
            //get a list od fabricant
            List<Fabricant> objFabricantList = _unitOfWork.Fabricant.GetAll().ToList();
            //to pass a data to a view
            return View(objFabricantList);
        }

        //add a new action method called create 
        public IActionResult Create()
        {
            return View();
        }

        //add a new action method called create with parameter to get submit data
        [HttpPost]
        public IActionResult Create(Fabricant obj)
        {
            if (obj.Description?.Length > 200)
            {
                ModelState.AddModelError("description", "la description ne doit pas dépasser 200 charactères!");
            }
            //check if model "fabricant" is valid with all requirement
            if (ModelState.IsValid)
            {
                //add a new fabricant
                _unitOfWork.Fabricant.Add(obj);
                //saves a changes in database
                _unitOfWork.Save();
                _notifyService.Success("Fabricant crée avec succes!");
                //return to index view and reload data
                return RedirectToAction("Index");
            }
            return View();
        }

        //add a new action method called Edit : get
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //Fabricant? fabricantFromDb = _db.Fabricants.Find(id);
            Fabricant? fabricantFromDb1 = _unitOfWork.Fabricant.Get(u => u.Id == id);
            if (fabricantFromDb1 == null)
            {
                return NotFound();
            }
            return View(fabricantFromDb1);
        }

        //add a new action method called Edit with parameter to get submit data
        [HttpPost]
        public IActionResult Edit(Fabricant obj)
        {
            if (obj.Description?.Length > 200)
            {
                ModelState.AddModelError("description", "la description ne doit pas dépasser 200 charactères!");
            }
            //check if model "fabricant" is valid with all requirement
            if (ModelState.IsValid)
            {
                //add a new fabricant
                _unitOfWork.Fabricant.Update(obj);
                //saves a changes in database
                _unitOfWork.Save();
                _notifyService.Success("Fabricant modifié avec succes!");
                //return to index view and reload data
                return RedirectToAction("Index");
            }
            return View();
        }


        //add a new action method called Delete : get
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //Fabricant? fabricantFromDb = _db.Fabricants.Find(id);
            Fabricant? fabricantFromDb1 = _unitOfWork.Fabricant.Get(u => u.Id == id);
            if (fabricantFromDb1 == null)
            {
                return NotFound();
            }
            return View(fabricantFromDb1);
        }

        //add a new action method called Delete with parameter to get submit data
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Fabricant? obj = _unitOfWork.Fabricant.Get(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.Fabricant.Remove(obj);
            _unitOfWork.Save();
            _notifyService.Success("Fabricant supprimé avec succes!");
            return RedirectToAction("Index");
        }
    }
}

TirelireWeb/Views/Fabricant/Create.cshtml
@model Fabricant

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Ajouter un fabricant
            </h2>
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3 row p-1">
            <label asp-for="Name" class="p-0"></label>
            <input asp-for="Name" type="text" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Description" class="p-0"></label>
            <input asp-for="Description" type="text" class="form-control" />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Pays" class="p-0"></label>
            <input asp-for="Pays" type="text" class="form-control" />
            <span asp-validation-for="Pays" class="text-danger"></span>
        </div>
        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-dark form-control">
                    Ajouter
                </button>
            </div>
            <div class="col-6 col-md-3 ">
                <a asp-controller="Fabricant" asp-action="Index" class="btn btn-secondary border form-control">
                    Back to Fabricant
                </a>
            </div>
        </div>

    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

TirelireWeb/Views/Fabricant/Delete.cshtml
@model Fabricant

<form method="post">
    <input asp-for="Id" hidden/>
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Delete un fabricant
            </h2>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Name" class="p-0"></label>
            <input asp-for="Name" type="text" disabled class="form-control" />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Description" class="p-0"></label>
            <input asp-for="Description" type="text" disabled class="form-control" />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Pays" class="p-0"></label>
            <input asp-for="Pays" type="text" disabled class="form-control" />
        </div>
        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-danger form-control">
                    Delete
                </button>
            </div>
            <div class="col-6 col-md-3 ">
                <a asp-controller="Fabricant" asp-action="Index" class="btn btn-secondary border form-control">
                    Back to Fabricant
                </a>
            </div>
        </div>

    </div>
</form>

TirelireWeb/Views/Fabricant/Edit.cshtml
@model Fabricant

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Editer un fabricant
            </h2>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Name" class="p-0"></label>
            <input asp-for="Name" type="text" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Description" class="p-0"></label>
            <input asp-for="Description" type="text" class="form-control" />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Pays" class="p-0"></label>
            <input asp-for="Pays" type="text" class="form-control" />
            <span asp-validation-for="Pays" class="text-danger"></span>
        </div>
        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-dark form-control">
                    Update
                </button>
            </div>
            <div class="col-6 col-md-3 ">
                <a asp-controller="Fabricant" asp-action="Index" class="btn btn-secondary border form-control">
                    Back to Fabricant
                </a>
            </div>
        </div>

    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

TirelireWeb/Views/Fabricant/Index.cshtml
<!--access model with lowercase-->
@model List<Fabricant>

<div class="container">
    <div class="row pt-4 pb-3">
        <div class="col-6">
            <h2 class="text-primary">
                Liste des Fabricants
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Fabricant" asp-action="Create" class="btn btn-dark">
                <i class="bi bi-plus-square"></i> Ajouter un fabricant
            </a>
        </div>
    </div>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>
                    Nom du fabricant
                </th>
                <th>
                    Description
                </th>
                <th>Pays</th>
            </tr>
        </thead>
        <tbody>
            <!--retrieve data from model with Uppercase "Model"-->
            @foreach (var obj in Model)
            {
                <tr>
                    <td>@obj.Name</td>
                    <td>
                        @obj.Description
                    </td>
                    <td>@obj.Pays</td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Fabricant" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                                <i class="bi bi-pencil-square"></i> Edit
                            </a>
                            <a asp-controller="Fabricant" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
                                <i class="bi bi-trash3"></i> Delete
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>